//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace OneSchool.Core.UmbracoModels
{
	/// <summary>Course</summary>
	[PublishedModel("course")]
	public partial class Course : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "course";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Course, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Course(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Body Schedule
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bodySchedule")]
		public string BodySchedule => this.Value<string>("bodySchedule");

		///<summary>
		/// Body Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("bodyTitle")]
		public string BodyTitle => this.Value<string>("bodyTitle");

		///<summary>
		/// Comments
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("comments")]
		public Comments Comments => this.Value<Comments>("comments");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("content")]
		public Skybrud.Umbraco.GridData.GridDataModel Content => this.Value<Skybrud.Umbraco.GridData.GridDataModel>("content");

		///<summary>
		/// Courses
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("courses")]
		public CourseList Courses => this.Value<CourseList>("courses");

		///<summary>
		/// Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("heroBackgroundImage")]
		public IPublishedContent HeroBackgroundImage => this.Value<IPublishedContent>("heroBackgroundImage");

		///<summary>
		/// Sub Titles
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("heroSubTitles")]
		public IEnumerable<PageHeaderSubTitle> HeroSubTitles => this.Value<IEnumerable<PageHeaderSubTitle>>("heroSubTitles");

		///<summary>
		/// Hero Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("heroTitle")]
		public string HeroTitle => this.Value<string>("heroTitle");

		///<summary>
		/// Comment Count
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryCommentCount")]
		public int SummaryCommentCount => this.Value<int>("summaryCommentCount");

		///<summary>
		/// Summary Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryDescription")]
		public string SummaryDescription => this.Value<string>("summaryDescription");

		///<summary>
		/// Summary Duration
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryDuration")]
		public string SummaryDuration => this.Value<string>("summaryDuration");

		///<summary>
		/// Summary Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryImage")]
		public IPublishedContent SummaryImage => this.Value<IPublishedContent>("summaryImage");

		///<summary>
		/// Participation Count
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryParticipationCount")]
		public string SummaryParticipationCount => this.Value<string>("summaryParticipationCount");

		///<summary>
		/// Summary Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryPrice")]
		public string SummaryPrice => this.Value<string>("summaryPrice");

		///<summary>
		/// Summary Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("summaryTitle")]
		public string SummaryTitle => this.Value<string>("summaryTitle");

		///<summary>
		/// Teacher
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("teacher")]
		public IPublishedContent Teacher => this.Value<IPublishedContent>("teacher");
	}
}
