//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace YuzuDelivery.UmbracoModels
{
	/// <summary>Course</summary>
	[PublishedModel("course")]
	public partial class Course : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "course";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Course, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Course(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// CommentForm Form
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("commentFormForm")]
		public object CommentFormForm => this.Value("commentFormForm");

		///<summary>
		/// CommentForm Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("commentFormTitle")]
		public string CommentFormTitle => this.Value<string>("commentFormTitle");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("content")]
		public global::Skybrud.Umbraco.GridData.GridDataModel Content => this.Value<global::Skybrud.Umbraco.GridData.GridDataModel>("content");

		///<summary>
		/// Courses
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("courses")]
		public global::YuzuDelivery.UmbracoModels.CourseList Courses => this.Value<global::YuzuDelivery.UmbracoModels.CourseList>("courses");

		///<summary>
		/// Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("headerBackgroundImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeaderBackgroundImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("headerBackgroundImage");

		///<summary>
		/// Sub Titles
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("headerSubTitles")]
		public global::System.Collections.Generic.IEnumerable<global::YuzuDelivery.UmbracoModels.PageHeaderSubTitle> HeaderSubTitles => this.Value<global::System.Collections.Generic.IEnumerable<global::YuzuDelivery.UmbracoModels.PageHeaderSubTitle>>("headerSubTitles");

		///<summary>
		/// Header Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("headerTitle")]
		public string HeaderTitle => this.Value<string>("headerTitle");

		///<summary>
		/// Comment Count
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryCommentCount")]
		public int SummaryCommentCount => this.Value<int>("summaryCommentCount");

		///<summary>
		/// Summary Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryDescription")]
		public string SummaryDescription => this.Value<string>("summaryDescription");

		///<summary>
		/// Summary Duration
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryDuration")]
		public string SummaryDuration => this.Value<string>("summaryDuration");

		///<summary>
		/// Summary Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent SummaryImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("summaryImage");

		///<summary>
		/// Participation Count
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryParticipationCount")]
		public string SummaryParticipationCount => this.Value<string>("summaryParticipationCount");

		///<summary>
		/// Summary Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryPrice")]
		public string SummaryPrice => this.Value<string>("summaryPrice");

		///<summary>
		/// Summary Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("summaryTitle")]
		public string SummaryTitle => this.Value<string>("summaryTitle");

		///<summary>
		/// Teacher
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("teacher")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Teacher => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("teacher");

		///<summary>
		/// Title Schedule
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("titleSchedule")]
		public string TitleSchedule => this.Value<string>("titleSchedule");

		///<summary>
		/// Title Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("titleTitle")]
		public string TitleTitle => this.Value<string>("titleTitle");
	}
}
